package plat_linux

// Nvme status codes
const (
	NVME_SC_SUCCESS = 0x0
	NVME_SC_INVALID_OPCODE = 0x1
	NVME_SC_ONVALID_FIELD = 0x2
	NVME_SC_CMDID_CONFLICT = 0x3
	NVME_SC_DARA_XFER_ERROR = 0x4
	NVME_SC_POWER_LOSS = 0x5
	NVME_SC_INTERNAL = 0x6
	NVME_SC_ABORT_REQ = 0x7
	NVME_SC_ABORT_QUEUE = 0x8
	NVME_SC_FUSED_FAIL = 0x9
	NVME_SC_FUSE_MISSING = 0xa
	NVME_SC_INVALID_NS = 0xb
	NVME_SC_CMD_SEQ_ERROR = 0xc
	NVME_SC_SGL_INVALID_LAST = 0xd
	NVME_SC_SGL_INVALID_COUNT = 0xe
)