name: Build Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Display Go version
        run: go version

      - run: mkdir -p output

      - name: Build For Windows
        run: |
          GOOS=windows GOARCH=amd64 go test github.com/jc-lab/go-dparm/...
      - name: Build For Linux
        run: |
          GOOS=linux GOARCH=amd64 go test github.com/jc-lab/go-dparm/...
